<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <RootNamespace>Checador_FXE</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>False</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SignAssembly>False</SignAssembly>
    <DelaySign>False</DelaySign>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.4.5" />
    <PackageReference Include="MySql.Data" Version="9.6.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SpreadsheetLight" Version="3.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Documents\Proyectos\Luz Paulina´s ManageEngine\Flow-ERP\FlowControls\FlowControls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Flow Common Workcore">
      <HintPath>..\..\..\..\Documents\Proyectos\Luz Paulina´s ManageEngine\Flow-ERP\Flow Common Workcore\bin\Debug\net6.0-windows\Flow Common Workcore.dll</HintPath>
    </Reference>
    <Reference Include="FlowControls">
      <HintPath>..\..\..\..\Documents\Proyectos\Luz Paulina´s ManageEngine\Flow-ERP\FlowControls\bin\Debug\net6.0-windows\FlowControls.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>