<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <RootNamespace>Checador_FXE</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>False</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SignAssembly>False</SignAssembly>
    <DelaySign>False</DelaySign>
    <Platforms>AnyCPU;x64</Platforms>

	<ManualVersion>1.0.1</ManualVersion>  
	<VersionSuffix>beta-dev</VersionSuffix>
	<AssemblyVersion>$(ManualVersion).$([System.DateTime]::Now.ToString('yyMM'))</AssemblyVersion>
	<InformationalVersion>$(AssemblyVersion)-$(VersionSuffix)</InformationalVersion>
	  <Description>Generador y gestor de asistencias de personal sindicalizado FXE con hardware ZKTeco.</Description>
	  
	<Copyright>Arturo Venegas IDC</Copyright>

	<NeutralLanguage>es-MX</NeutralLanguage>
	<RepositoryType>git</RepositoryType>
	<RepositoryUrl>https://github.com/ArturoProgrammer/Checador-FXE</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.20.0" />
    <PackageReference Include="FlowCommonWorkcore" Version="1.0.16" />
    <PackageReference Include="FlowControls" Version="1.0.15.36" />
    <PackageReference Include="iTextSharp" Version="5.4.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SpreadsheetLight.Fork" Version="3.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="frmCrudRelacionHorariosViewer.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="frmCrudRelacionHorarios.cs" />
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>