; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Checador FXE"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "Arturo Venegas IDC"
#define MyAppURL "soporte.hermosillo@ferromex.mx"
#define MyAppExeName "Checador FXE.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".caf"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8A3EA8BA-4C70-4C40-B6DE-27F244BAFF79} }
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\LENOVO\Documents\Proyectos
OutputBaseFilename=ChecadorFxe-v1.0.1_x64
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\BCrypt.Net-Next.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\BouncyCastle.Crypto.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\BouncyCastle.Cryptography.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Checador FXE.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Checador FXE.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Checador FXE.dll.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Checador FXE.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Checador FXE.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Checador FXE.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\DocumentFormat.OpenXml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Flow Common Workcore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\FlowControls.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Google.Protobuf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\ICSharpCode.TextEditor.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\itextsharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\K4os.Compression.LZ4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\K4os.Compression.LZ4.Streams.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\K4os.Hash.xxHash.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Markdig.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Microsoft.Extensions.ObjectPool.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Microsoft.Web.WebView2.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Microsoft.Web.WebView2.WinForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Microsoft.Web.WebView2.Wpf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\MySql.Data.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\SpreadsheetLight.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.ComponentModel.Composition.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.ComponentModel.Composition.Registration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Data.Odbc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Data.OleDb.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Data.SqlClient.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.DirectoryServices.AccountManagement.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.DirectoryServices.Protocols.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Drawing.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.IO.Pipelines.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.IO.Ports.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Management.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Private.ServiceModel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Reflection.Context.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Runtime.Caching.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.ServiceModel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.ServiceModel.Duplex.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.ServiceModel.Http.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.ServiceModel.NetTcp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.ServiceModel.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.ServiceModel.Security.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.ServiceModel.Syndication.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.ServiceProcess.ServiceController.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Speech.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Text.Encodings.Web.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Text.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\System.Web.Services.Description.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\ZstdSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\cs\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\de\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\es\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\fr\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\it\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\ja\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\ko\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\pl\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\pt-BR\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\ru\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\runtimes\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\tr\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\zh-Hans\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\zh-Hant\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\FORMATO_ASISTENCIA_TAB_1_15_form.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\LENOVO\Documents\Proyectos\Checador-FXE\Checador FXE\bin\x64\Release\net8.0-windows7.0\FORMATO_ASISTENCIA_TAB_16_31_form.pdf"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

