//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checador_FXE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""1"":{""titulo"":""Turno corrido"",""primer_horario"":{""entrada"":800,""salida"":1500},""segundo_horario"":{""entrada"":0,""salida"":0},""tiempo_extra"":{""entrada"":0,""salida"":0}},""2"":{""titulo"":""Turno completo con comida"",""primer_horario"":{""entrada"":800,""salida"":1300},""segundo_horario"":{""entrada"":1500,""salida"":1700},""tiempo_extra"":{""entrada"":0,""salida"":0}},""3"":{""titulo"":""Media tarde"",""primer_horario"":{""entrada"":1500,""salida"":1700},""segundo_horario"":{""entrada"":0,""salida"":0},""tiempo_extra"":{""entrada"":0,""salida"":0}}}")]
        public string TURNOS_HORARIOS {
            get {
                return ((string)(this["TURNOS_HORARIOS"]));
            }
            set {
                this["TURNOS_HORARIOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int MINUTOS_TOLERANCIA {
            get {
                return ((int)(this["MINUTOS_TOLERANCIA"]));
            }
            set {
                this["MINUTOS_TOLERANCIA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ABRIR_SIEMPRE_AL_GENERAR {
            get {
                return ((bool)(this["ABRIR_SIEMPRE_AL_GENERAR"]));
            }
            set {
                this["ABRIR_SIEMPRE_AL_GENERAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hermosillo")]
        public string LUGAR_REMITENTE_DEFAULT {
            get {
                return ((string)(this["LUGAR_REMITENTE_DEFAULT"]));
            }
            set {
                this["LUGAR_REMITENTE_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hermosillo")]
        public string DIVISION_REMITENTE_DEFAULT {
            get {
                return ((string)(this["DIVISION_REMITENTE_DEFAULT"]));
            }
            set {
                this["DIVISION_REMITENTE_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZKTECO K40 KIT")]
        public string DISPOSITIVO_DEFAULT {
            get {
                return ((string)(this["DISPOSITIVO_DEFAULT"]));
            }
            set {
                this["DISPOSITIVO_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Azul")]
        public string COLOR_PINCEL {
            get {
                return ((string)(this["COLOR_PINCEL"]));
            }
            set {
                this["COLOR_PINCEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sufragio")]
        public string LOCALIDAD_DEFAULT {
            get {
                return ((string)(this["LOCALIDAD_DEFAULT"]));
            }
            set {
                this["LOCALIDAD_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.10.129.127")]
        public string SERVER_HOSTNAME {
            get {
                return ((string)(this["SERVER_HOSTNAME"]));
            }
            set {
                this["SERVER_HOSTNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rmt_checador_fxe")]
        public string SERVER_USER {
            get {
                return ((string)(this["SERVER_USER"]));
            }
            set {
                this["SERVER_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F3rr0m3x2026*")]
        public string SERVER_PASS {
            get {
                return ((string)(this["SERVER_PASS"]));
            }
            set {
                this["SERVER_PASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string SERVER_PORT {
            get {
                return ((string)(this["SERVER_PORT"]));
            }
            set {
                this["SERVER_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reporte de Asistencias")]
        public string DEFAULT_FILENAME {
            get {
                return ((string)(this["DEFAULT_FILENAME"]));
            }
            set {
                this["DEFAULT_FILENAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TURNO_DEFECTO {
            get {
                return ((string)(this["TURNO_DEFECTO"]));
            }
            set {
                this["TURNO_DEFECTO"] = value;
            }
        }
    }
}
